[workspace]
resolver = "3"
members = [
    "controller-core",
    "emulator",
    "firmware",
]

[workspace.dependencies]
embassy-sync = "0.7.2"
embassy-time = "0.5.0"
heapless = "0.8.0"
logos = { version = "0.14", default-features = false }
winnow = { version = "0.6", default-features = false }
