[package]
name = "controller-emulator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "controller-emulator"
path = "src/main.rs"

[dependencies]
controller-core = { path = "../controller-core", features = ["alloc"] }
crossterm = "0.27"
